const mongoose = require('mongoose');

// Middleware
const requireLogin = require('../middleware/requireLogin');
const requireCredits = require('../middleware/requireCredits');

const Mailer = require('../services/Mailer');

// Survey template
const surveyTemplate = require('../services/emailTemplates/surveyTemplate');

// models
const Survey = mongoose.model('surveys');

module.exports = (app) => {
  app.post('/api/surveys', requireLogin, requireCredits, async (req, res) => {
    // ES6 destructuring
    const { title, subject, body, recipients } = req.body;

    const survey = new Survey({
      // These don't need to assigned from the variables above due to ES6 magic..
      title,
      subject,
      body,
      // Takes list of CSV emails, split them into an array, based on comma location, and map them into an array of objects with a property of 'email' and corresponding string value.
      recipients: recipients
        .split(',')
        .map((email) => ({ email: email.trim() })),
      // Returns the autogenerated MongodDb user id.
      _user: req.user.id,
      dateSent: Date.now(),
    });

    try {
      const mailer = new Mailer(survey, surveyTemplate(survey));
  
      // Send survey to recipients via SendGrid
      await mailer.send();
  
      // Persist survey to DB.
      survey.save();
  
      // Deduct credit from user
      req.user.credits -= 1;
      const user = await req.user.save();
  
      res.send(user);
      
    } catch (error) {
      res.status(422).send(error);
    }
  });
};
